### ISSUE TITLE
Messages with attachments sometimes translate as "This message contains an interactive element."

### ISSUE THREAD

**Issue by kenneyd** [seratch/deepl-for-slack#25]
The attempt here is to translate a Japanese message to English that includes a png image attachement. 

Expected behaviour is that the attachment is ignored, and just the text is translated, but I guess the Slack API is here is returning the text "This message contains an interactive element." and this translate bot is failing on this "interactive" input instead.

<img width="347" alt="image" src="https://github.com/seratch/deepl-for-slack/assets/16775438/1e92f519-b766-40dd-bf35-ac64a52ac183">

**Comment by seratch** [comment]
Hey @kenneyd, thanks for writing in! 

This seems to be due to some changes on the Slack platform side. As far as I'm aware, many people have already raised the same concern with Slack. Therefore, I believe this issue will be resolved soon. This project doesn't involve any actions we can take to resolve it, so I'm going to close this issue on our end.

Thanks again for sharing this (and using this app!)
